### ISSUE TITLE
Can't click on a mapping hex under a hotspot hex

### ISSUE THREAD

**Issue by old-square-eyes** [helium/mappers#100]
The big hotspot hexes seem to block the smaller mapping hexes. I'm on Firefox/Mac OS.

Edit: Ahhh I figured it out. It only doesn't work if the hotspot hex is highlighted as a witness already.
You have to click off until the line disappears. Then you can click back on the mapping hex you wanted. This is still pretty unusable if you want to get to a mapping hex under a heavily witnessed hotspot.

**Comment by mcauser** [comment]
Is this a duplicate of #95?

**Comment by old-square-eyes** [comment]
Yep sorry will close
