### ISSUE TITLE
Add Option to Clear Upinks Heard Layers

### ISSUE THREAD

**Issue by kent-williams** [helium/mappers#50]

**Comment by jthiller** [comment]
Need UI for this? I was thinking that closing the info pane could clear the map selection. We could introduce a 'collapse' button to preserve the map selection but hide the info pane. 
![image](https://user-images.githubusercontent.com/1965053/123200150-0d9b5080-d465-11eb-9201-3ae1e8960abc.png)

**Comment by kent-williams** [comment]
I was thinking the same!

**Comment by jthiller** [comment]
Via Siegfried in community chat: 
> ability to deselect a selected mapped hex by tapping/double tapping again

I think this could be implemented as a tap to select/ tap to deselect - like a checkbox. It'd be a good additional interaction alongside the collapse/close buttons.
