### ISSUE TITLE
Calculate 'Best RSSI/SNR' from uplinks list 

### ISSUE THREAD

**Issue by jthiller** [helium/mappers#51]
Value currently comes from the hex value which may be out of date due to the realtime updating.
This value is easy enough to get from the max() of the uplinks list.

See below, 'best rssi' is -95dbm while -92dbm is available in the list.
![image](https://user-images.githubusercontent.com/1965053/123199530-e7c17c00-d463-11eb-87c7-b56c4b3b0cbc.png)

**Comment by kent-williams** [comment]
@jthiller would you mind checking this again, I thought I had fixed it and I can't find a hex that an incorrect best.

**Comment by jthiller** [comment]
This was mainly happening while I was actively mapping. I'll test it again tomorrow.

**Comment by kent-williams** [comment]
Ok good to know. In theory the best out of all uplinks heard should be getting set for the hex still.

**Comment by kent-williams** [comment]
I'm going to close this for now as we haven't heard of more occurrences.
