### ISSUE TITLE
Ability to link to specific hex.

### ISSUE THREAD

**Issue by jthiller** [helium/mappers#60]
It would be useful to allow users to link to specific hexes in the map. We can encode the h3 index as a url param and zoom to it on page load.

e.g. `mappers.helium.com/?selectedH3=8c2a306719217ffff`

We may also want to provide users a quick 'copy' button for the current hex. This also improves the experience for users that have the page set up as a progressive web app. 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/1965053/123883299-97339e00-d8fd-11eb-911f-c0d229077096.png">

**Comment by mpkogli** [comment]
Love it. Perhaps also a url parameter to specify whether or not to show the witness lines from a given hex (for those who want to open the page at a given point but not automatically display the Hex Stats).

**Comment by jthiller** [comment]
> url parameter to specify whether or not to show the witness lines from a given hex

Good clarification. I could see that looking something like 
`mappers.helium.com/?h3=8c2a306719217ffff&selected=true`

**Comment by kent-williams** [comment]
Closing this with #92
