### ISSUE TITLE
Add the date to the Hotspot details table

### ISSUE THREAD

**Issue by akistem** [helium/mappers#62]
It would be nice to see the date that the RSSI and SNR were witnessed for each hotspot when clicking on the hex details. And to sort by most recent value.

**Comment by CraigGorton** [comment]
In addition, the Hex Statistics should show the date that the hex was last mapped.

**Comment by jthiller** [comment]
Thanks for filing this @akistem. 
I've gone ahead and added the date to the info pane, but not on each uplink for now. I'd ideally like to reserve that space for the uplink distance in this release. For a v3 release I am imagining the more fine-tuned controls such as uplink sorting like you're suggesting.
