### ISSUE TITLE
Delete mapping data following new location assert

### ISSUE THREAD

**Issue by snip** [helium/mappers#64]
When a hotspot owner move the hotspot location by creating a new assert, related mapped data should be ignored as this mapping is no more relevant.
As an example `Short Inky Butterfly` was moved months ago by 500km away and its old mapped data is still displayed in area without any other hotspot.

**Comment by kent-williams** [comment]
Most mappers nowadays contribute with more than one uplink heard per transmission. Given this redundancy, I do not believe completely removing all the data is necessary in the majority of cases. In the next version of mappers we do hope to add decaying data and other filters that would better address this. Going to close this for now.
