### ISSUE TITLE
Live tiles only viewable at certain zoom levels

### ISSUE THREAD

**Issue by jthiller** [helium/mappers#73]
When new hexes are added to the map, they do not appear in the active zoom level – making it appear as though no signal was received from a newly mapped area.

Interestingly, the hexes DO appear after changing zoom levels - usually zooming in.
![HexShow](https://user-images.githubusercontent.com/1965053/127075848-e0aec06e-1111-4271-bcf9-b38f6834ac70.gif)

I've also witnessed some rendering artifacts where an entire hex is not drawn. This might just be unrelated.
<img width="360" alt="image" src="https://user-images.githubusercontent.com/1965053/127076126-8eebb01c-f978-4731-83e2-e09430029326.png">

Fixing this issue will be necessary for #55 / #72 to be successful.

**Comment by jthiller** [comment]
Further exploration - though inconclusive... This might only be related to the geolocate function or how I've implemented it. Just ran some tests and was not seeing the rendering issue on production.

**Comment by kent-williams** [comment]
Well that would be a welcome fix! On production or the review deploy?

**Comment by jthiller** [comment]
Production seems to be working as expected.

The branch deploy is where I consistently see issues.

**Comment by jthiller** [comment]
Oh, yea. I'm fairly convinced this is related to something with my branch.
