### ISSUE TITLE
Add Full Install Instructions to Readme

### ISSUE THREAD

**Issue by kent-williams** [helium/mappers#76]

**Comment by mgrog** [comment]
Some things I encountered in the setup which might help in the instructions:

I ran into an issue with `$ mix echo.setup` where it failed on compiling the h3 dependency. To resolve, I needed to install [cmake](https://cmake.org/install/) and add it to PATH.

Also, if you have used brew to install Postgres (macOS) you might need to run this cmd to resolve an issue when creating the database:
`$ /usr/local/opt/postgres/bin/createuser -s postgres`

**Comment by KevJames** [comment]
Getting this error when running $ mix echo.setup (this is after I installed cmake as I was also getting the same error as mgrog above): 
12:28:24.692 [error] GenServer #PID<0.5723.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.3.1) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Mappers.Repo couldn't be created: killed

**Comment by kent-williams** [comment]
Added to readme, closing
