### ISSUE TITLE
Tracker registration error.

### ISSUE THREAD

**Issue by DmitryX1** [helium/mappers#89]
I cannot register the tracker on the helium network.
Tracker RAK7200.
There is only one hotspot nearby.
https://explorer.helium.com/hotspots/112v2tJimiB7JrrjtXYsmYz1mH6UkNUJcxyMvoFFHZ8GqF1arjjV
The hot spot is mine, you have full access to it.

Assumption: the radio module is disabled in the hotspot, possibly due to regional restrictions.
Question: how to check the readiness of the hotspot to receive a radio signal?

![image](https://user-images.githubusercontent.com/91494885/143875899-2db89ce5-2f16-4f95-aba6-e2beb50aa213.png)
![image](https://user-images.githubusercontent.com/91494885/143877313-93b0c558-9a28-433d-baf6-2c3570c01c88.png)

**Comment by jthiller** [comment]
Hi, this is unrelated to the mappers project. Mappers only ingests data passed from Console - it does not handle device onboarding directly.

I suggest asking this question in the [Helium Discord](https://discord.gg/helium) in the #sensor-dev or #mappers channel.
